version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: halitr_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: halitr_user
      POSTGRES_PASSWORD: halitr_password
      POSTGRES_DB: halitr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - halitr_network

  redis:
    image: redis:7-alpine
    container_name: halitr_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - halitr_network

  api:
    build: .
    container_name: halitr_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://halitr_user:halitr_password@postgres:5432/halitr_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - halitr_network

volumes:
  postgres_data:
  redis_data:

networks:
  halitr_network:
    driver: bridge
